version: '3'
services:
    jenkins:
        build: ./jenkins
        volumes:
            - /var/run/docker.sock:/var/run/docker.sock
            - ../springapp:/pipeline-dev
        environment:
            JAVA_OPTS: -Djenkins.install.runSetupWizard=false
        ports:
            - "18080:8080"
